FROM oven/bun:1.2-alpine

WORKDIR /app

COPY frontend/package.json frontend/bun.lock* ./
RUN bun install --frozen-lockfile

COPY frontend/ .
COPY shared/ /shared

EXPOSE 5173

CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
